### ISSUE TITLE
Timezone issue

### ISSUE THREAD

**Issue by prabhjot636** [linkedin/pyexchange#35]
Hi, I have an issue regarding the timezone while using the pyExchange. I have provided the details here: https://stackoverflow.com/questions/28024646/timezone-issue-with-pyexchange

It would be great if anyone of you can have a look. Thanks and have a nice day!

**Comment by trustrachel** [comment]
Hi! Sorry for the bug, let me take a look.

**Comment by trustrachel** [comment]
I left an answer on SO here: http://stackoverflow.com/a/28056724/1819983

The short answer is I don't think it's a problem with pyexchange, but with your timezone handling. THe package is returning UTC dates for you instead of localtime, and that's why it looks like the dates are off by an hour (your tz is +1 UTC). 

Give that script a whirl and see if it fixes your problem. If not, feel free to come on back and reopen this and I'll take another look. Thanks!
